apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: helm-skaffold-demo
build:
  artifacts:
    - image: server
      context: app
  local:
    tryImportMissing: true
test:
  - image: server
    context: app
    custom:
      - command: npm run test
        timeoutSeconds: 1200
deploy:
  helm: {}
verify:
  - name: alpine-wget
    container:
      name: alpine-wget
      image: alpine:3.15.4
      command: ["/bin/sh"]
      args: ["-c", "wget http://www.google.com"]
profiles:
  - name: development
    activation:
      - command: dev
    build:
      artifacts:
      - image: server
        context: app
        docker:
          target: development
        sync:
          infer:
            - "src/*.js"
    manifests:
      helm:
        releases:
        - name: helm-skaffold-demo 
          chartPath: helm
          namespace: hsd-dev
          setValues:
            podLabels.env: development
          valuesFiles:
            - "helm/values.yaml"
          setValueTemplates:
            image: "{{.IMAGE_FULLY_QUALIFIED_server}}"
  - name: production
    manifests:
      helm:
        releases:
        - name: helm-skaffold-demo 
          chartPath: helm
          namespace: hsd
          setValues:
            podLabels.env: production
            replicas: 2
          valuesFiles:
            - "helm/values.yaml"
          setValueTemplates:
            image: "{{.IMAGE_FULLY_QUALIFIED_server}}"
