steps:
  # build images, package & push helm chart
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.3-lts
    args:
      - "skaffold"
      - "build"
      - "--file-output=/workspace/artifacts.json"
      - "--default-repo=$_CONTAINER_REGISTRY"
  # test
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.3-lts
    args:
      - "skaffold"
      - "test"
      - "--build-artifacts=/workspace/artifacts.json"
      - "--assume-yes"
  # deploy with skaffold
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.3-lts
    args:
      - "skaffold"
      - "deploy"
      - "--build-artifacts=/workspace/artifacts.json"
      - "--assume-yes"
  # verify deployment with skaffold
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.3-lts
    args:
      - "skaffold"
      - "verify"
      - "--build-artifacts=/workspace/artifacts.json"
options:
  logging: CLOUD_LOGGING_ONLY